spring:
  profiles:
    active: prod
  application:
    name: guessBuddy
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000 # 30 seconds
      max-lifetime: 1800000 # 30 minutes
      connection-timeout: 20000 # 20 seconds
      schema: app
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
      hibernate:
        SQL: ERROR
        type:
          descriptor:
            sql:
              BasicBinder: ERROR

server:
  port: 8080

authentication:
  whitelisted-endpoints:
    - /authentication/sign-up
    - /authentication/sign-in
    - /authentication/start-forgot-password

management:
  endpoints:
    web:
      exposure:
        include: "*"