spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000 # 30 seconds
      max-lifetime: 1800000 # 30 minutes
      connection-timeout: 20000 # 20 seconds
      schema: app
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  profiles:
    active: prod
  application:
    name: guessBuddy
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # Scheduler configuration
  task:
    scheduling:
      pool:
        size: 5
      thread-name-prefix: scheduled-task-
    execution:
      pool:
        core-size: 10
        max-size: 20
        queue-capacity: 100
      thread-name-prefix: async-task-

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
      hibernate:
        SQL: ERROR
        type:
          descriptor:
            sql:
              BasicBinder: ERROR

server:
  port: 8080

authentication:
  whitelisted-endpoints:
    - /authentication/sign-up
    - /authentication/sign-in
    - /authentication/start-forgot-password
    - /authentication/complete-forgot-password
    - /authentication/refresh-token

management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  content-filter:
    objectionable-words: "fuck,shit,damn,hell,ass,bitch,bastard,crap,piss,cock,dick,pussy,whore,slut,fag,nigger,retard,nazi,hitler,kill,die,murder,suicide,rape,sex,porn,xxx,spam,scam,fraud,siktir,amk,aq,amına,göt,yarak,yarrak,orospu,piç,ibne,amcık,çük,sik,pezevenk,gavat,kaltak,salak,gerizekalı,mal,aptal,puşt,kahpe,sikmek,sikeyim,siktirgit,amcığı,amını,sürtük,sürtüğü,fahişe,hayvan,eşek,eşşek,inek,hayvan"
    case-sensitive: false
    strict-mode: false
